# Generated by Django 5.2.1 on 2025-05-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='response_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
